package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class assessments implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("activeUser")
	private java.lang.String activeUser;
	@org.kie.api.definition.type.Label("assessmentCaseTime")
	private java.lang.Long assessmentCaseTime;
	@org.kie.api.definition.type.Label("assessmentOwner")
	private java.lang.String assessmentOwner;
	@org.kie.api.definition.type.Label("assessmentId")
	private java.lang.String assessmentId;
	@org.kie.api.definition.type.Label("assessmentCreator")
	private java.lang.String assessmentCreator;
	@org.kie.api.definition.type.Label("brand")
	private java.lang.String brand;
	@org.kie.api.definition.type.Label("brandDescription")
	private java.lang.String brandDescription;
	@org.kie.api.definition.type.Label("caseStatus")
	private java.lang.String caseStatus;
	@org.kie.api.definition.type.Label("containerId")
	private java.lang.String containerId;
	@org.kie.api.definition.type.Label("createdAt")
	private java.math.BigInteger createdAt;
	@org.kie.api.definition.type.Label("createdBy")
	private java.lang.String createdBy;
	@org.kie.api.definition.type.Label("delayReason")
	private java.lang.String delayReason;
	@org.kie.api.definition.type.Label("delayType")
	private java.lang.String delayType;
	@org.kie.api.definition.type.Label("dueDate")
	private java.lang.Long dueDate;
	@org.kie.api.definition.type.Label("imsPrefix")
	private java.lang.String imsPrefix;
	@org.kie.api.definition.type.Label("processId")
	private java.lang.String processId;
	@org.kie.api.definition.type.Label("processInstanceId")
	private Long processInstanceId;
	@org.kie.api.definition.type.Label("subBrand")
	private java.lang.String subBrand;
	@org.kie.api.definition.type.Label("subBrandDescription")
	private java.lang.String subBrandDescription;

	@org.kie.api.definition.type.Label("assessmentCustomerDetails")
	private com.myteam.tts_connected_claims.assessmentCustomerDetails assessmentCustomerDetails;

	@org.kie.api.definition.type.Label("assessmentPolicyDetails")
	private com.myteam.tts_connected_claims.assessmentPolicyDetails assessmentPolicyDetails;

	@org.kie.api.definition.type.Label("claimDetails")
	private com.myteam.tts_connected_claims.claimDetails claimDetails;

	@org.kie.api.definition.type.Label("channel")
	private com.myteam.tts_connected_claims.channel channel;

	@org.kie.api.definition.type.Label("classification")
	private com.myteam.tts_connected_claims.classification classification;

	@org.kie.api.definition.type.Label("resendAssessment")
	private java.lang.Boolean resendAssessment;

	@org.kie.api.definition.type.Label("riskItemSequenceNumber")
	private java.lang.String riskItemSequenceNumber;

	@org.kie.api.definition.type.Label("personSequenceNumber")
	private java.lang.String personSequenceNumber;

	@org.kie.api.definition.type.Label("caseClosedReason")
	private java.lang.String caseClosedReason;

	@org.kie.api.definition.type.Label("ownerGroupList")
	private java.util.List<java.lang.String> ownerGroupList;

	@org.kie.api.definition.type.Label("claimsData")
	private com.myteam.tts_connected_claims.claimsData claimsData;

	@org.kie.api.definition.type.Label("vastatus")
	private java.lang.String vastatus;

	@org.kie.api.definition.type.Label("triggerSource")
	private java.lang.String triggerSource;

	@org.kie.api.definition.type.Label("taskDashBoard")
	private java.lang.Boolean taskDashBoard;

	@org.kie.api.definition.type.Label("requestType")
	private java.lang.String requestType;

	@org.kie.api.definition.type.Label("refferedToLA")
	private java.lang.Boolean refferedToLA;

	@org.kie.api.definition.type.Label("timeline")
	private java.util.List<com.myteam.tts_connected_claims.timeline> timeline;

	@org.kie.api.definition.type.Label("groupList")
	private java.util.List<java.lang.String> groupList;

	@org.kie.api.definition.type.Label("completedByLA")
	private java.lang.Boolean completedByLA;

	@org.kie.api.definition.type.Label("caseCancelledReason")
	private java.lang.String caseCancelledReason;

	@org.kie.api.definition.type.Label("followUpCompleted")
	private java.lang.Boolean followUpCompleted;

	@org.kie.api.definition.type.Label("customerFollowUp")
	private java.lang.Boolean customerFollowUp;

	@org.kie.api.definition.type.Label("appIncidentDescription")
	private java.lang.String appIncidentDescriptiona;

	@org.kie.api.definition.type.Label("location")
	private java.lang.String location;

	@org.kie.api.definition.type.Label("stolenItemDetails")
	private com.myteam.tts_connected_claims.stolenItemDetails stolenItemDetails;

	@org.kie.api.definition.type.Label("documentList")
	private java.util.List<java.lang.String> documentList;

	@org.kie.api.definition.type.Label("incidentCaseId")
	private java.lang.String incidentCaseId;

	@org.kie.api.definition.type.Label("nonMotorClaimStatus")
	private java.lang.String nonMotorClaimStatus;

	@org.kie.api.definition.type.Label("sentDate")
	private java.lang.Long sentDate;

	@org.kie.api.definition.type.Label("tpDriverDetails")
	private java.util.List<java.lang.String> tpDriverDetails;

	@org.kie.api.definition.type.Label("vehicleDamageAreaAssessment")
	private java.lang.Boolean vehicleDamageAreaAssessment;

	@org.kie.api.definition.type.Label("vehicleInnerDamage")
	private com.myteam.tts_connected_claims.vehicleInnerDamage vehicleInnerDamage;

	@org.kie.api.definition.type.Label("vehicleOuterDamage")
	private com.myteam.tts_connected_claims.vehicleOuterDamage vehicleOuterDamage;

	@org.kie.api.definition.type.Label("coverType")
	private com.myteam.tts_connected_claims.coverType coverType;

	@org.kie.api.definition.type.Label("completeReview")
	private java.lang.Boolean completeReview;

	@org.kie.api.definition.type.Label(value = "appAdditionalComments")
	private java.lang.String appAdditionalComments;

	public assessments() {
	}

	public java.lang.String getActiveUser() {
		return this.activeUser;
	}

	public void setActiveUser(java.lang.String activeUser) {
		this.activeUser = activeUser;
	}

	public java.lang.Long getAssessmentCaseTime() {
		return this.assessmentCaseTime;
	}

	public void setAssessmentCaseTime(java.lang.Long assessmentCaseTime) {
		this.assessmentCaseTime = assessmentCaseTime;
	}

	public java.lang.String getAssessmentOwner() {
		return this.assessmentOwner;
	}

	public void setAssessmentOwner(java.lang.String assessmentOwner) {
		this.assessmentOwner = assessmentOwner;
	}

	public java.lang.String getAssessmentId() {
		return this.assessmentId;
	}

	public void setAssessmentId(java.lang.String assessmentId) {
		this.assessmentId = assessmentId;
	}

	public java.lang.String getAssessmentCreator() {
		return this.assessmentCreator;
	}

	public void setAssessmentCreator(java.lang.String assessmentCreator) {
		this.assessmentCreator = assessmentCreator;
	}

	public java.lang.String getBrand() {
		return this.brand;
	}

	public void setBrand(java.lang.String brand) {
		this.brand = brand;
	}

	public java.lang.String getBrandDescription() {
		return this.brandDescription;
	}

	public void setBrandDescription(java.lang.String brandDescription) {
		this.brandDescription = brandDescription;
	}

	public java.lang.String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(java.lang.String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public java.math.BigInteger getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.math.BigInteger createdAt) {
		this.createdAt = createdAt;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
	}

	public java.lang.String getDelayReason() {
		return this.delayReason;
	}

	public void setDelayReason(java.lang.String delayReason) {
		this.delayReason = delayReason;
	}

	public java.lang.String getDelayType() {
		return this.delayType;
	}

	public void setDelayType(java.lang.String delayType) {
		this.delayType = delayType;
	}

	public java.lang.Long getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.lang.Long dueDate) {
		this.dueDate = dueDate;
	}

	public java.lang.String getImsPrefix() {
		return this.imsPrefix;
	}

	public void setImsPrefix(java.lang.String imsPrefix) {
		this.imsPrefix = imsPrefix;
	}

	public java.lang.String getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.String processId) {
		this.processId = processId;
	}

	public java.lang.String getSubBrand() {
		return this.subBrand;
	}

	public void setSubBrand(java.lang.String subBrand) {
		this.subBrand = subBrand;
	}

	public java.lang.String getSubBrandDescription() {
		return this.subBrandDescription;
	}

	public void setSubBrandDescription(java.lang.String subBrandDescription) {
		this.subBrandDescription = subBrandDescription;
	}

	public com.myteam.tts_connected_claims.assessmentCustomerDetails getAssessmentCustomerDetails() {
		return this.assessmentCustomerDetails;
	}

	public void setAssessmentCustomerDetails(
			com.myteam.tts_connected_claims.assessmentCustomerDetails assessmentCustomerDetails) {
		this.assessmentCustomerDetails = assessmentCustomerDetails;
	}

	public com.myteam.tts_connected_claims.assessmentPolicyDetails getAssessmentPolicyDetails() {
		return this.assessmentPolicyDetails;
	}

	public void setAssessmentPolicyDetails(
			com.myteam.tts_connected_claims.assessmentPolicyDetails assessmentPolicyDetails) {
		this.assessmentPolicyDetails = assessmentPolicyDetails;
	}

	public com.myteam.tts_connected_claims.claimDetails getClaimDetails() {
		return this.claimDetails;
	}

	public void setClaimDetails(
			com.myteam.tts_connected_claims.claimDetails claimDetails) {
		this.claimDetails = claimDetails;
	}

	public com.myteam.tts_connected_claims.channel getChannel() {
		return this.channel;
	}

	public void setChannel(com.myteam.tts_connected_claims.channel channel) {
		this.channel = channel;
	}

	public com.myteam.tts_connected_claims.classification getClassification() {
		return this.classification;
	}

	public void setClassification(
			com.myteam.tts_connected_claims.classification classification) {
		this.classification = classification;
	}

	public java.lang.Boolean getResendAssessment() {
		return this.resendAssessment;
	}

	public void setResendAssessment(java.lang.Boolean resendAssessment) {
		this.resendAssessment = resendAssessment;
	}

	public java.lang.String getRiskItemSequenceNumber() {
		return this.riskItemSequenceNumber;
	}

	public void setRiskItemSequenceNumber(
			java.lang.String riskItemSequenceNumber) {
		this.riskItemSequenceNumber = riskItemSequenceNumber;
	}

	public java.lang.String getPersonSequenceNumber() {
		return this.personSequenceNumber;
	}

	public void setPersonSequenceNumber(java.lang.String personSequenceNumber) {
		this.personSequenceNumber = personSequenceNumber;
	}

	public java.lang.String getCaseClosedReason() {
		return this.caseClosedReason;
	}

	public void setCaseClosedReason(java.lang.String caseClosedReason) {
		this.caseClosedReason = caseClosedReason;
	}

	public java.util.List<java.lang.String> getOwnerGroupList() {
		return this.ownerGroupList;
	}

	public void setOwnerGroupList(
			java.util.List<java.lang.String> ownerGroupList) {
		this.ownerGroupList = ownerGroupList;
	}

	public com.myteam.tts_connected_claims.claimsData getClaimsData() {
		return this.claimsData;
	}

	public void setClaimsData(
			com.myteam.tts_connected_claims.claimsData claimsData) {
		this.claimsData = claimsData;
	}

	public java.lang.String getVastatus() {
		return this.vastatus;
	}

	public void setVastatus(java.lang.String vastatus) {
		this.vastatus = vastatus;
	}

	public java.lang.String getTriggerSource() {
		return this.triggerSource;
	}

	public void setTriggerSource(java.lang.String triggerSource) {
		this.triggerSource = triggerSource;
	}

	public java.lang.Boolean getTaskDashBoard() {
		return this.taskDashBoard;
	}

	public void setTaskDashBoard(java.lang.Boolean taskDashBoard) {
		this.taskDashBoard = taskDashBoard;
	}

	public java.lang.String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(java.lang.String requestType) {
		this.requestType = requestType;
	}

	public java.lang.Boolean getRefferedToLA() {
		return this.refferedToLA;
	}

	public void setRefferedToLA(java.lang.Boolean refferedToLA) {
		this.refferedToLA = refferedToLA;
	}

	public java.util.List<com.myteam.tts_connected_claims.timeline> getTimeline() {
		return this.timeline;
	}

	public void setTimeline(
			java.util.List<com.myteam.tts_connected_claims.timeline> timeline) {
		this.timeline = timeline;
	}

	public java.util.List<java.lang.String> getGroupList() {
		return this.groupList;
	}

	public void setGroupList(java.util.List<java.lang.String> groupList) {
		this.groupList = groupList;
	}

	public java.lang.Boolean getCompletedByLA() {
		return this.completedByLA;
	}

	public void setCompletedByLA(java.lang.Boolean completedByLA) {
		this.completedByLA = completedByLA;
	}

	public java.lang.String getCaseCancelledReason() {
		return this.caseCancelledReason;
	}

	public void setCaseCancelledReason(java.lang.String caseCancelledReason) {
		this.caseCancelledReason = caseCancelledReason;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.Boolean getFollowUpCompleted() {
		return this.followUpCompleted;
	}

	public void setFollowUpCompleted(java.lang.Boolean followUpCompleted) {
		this.followUpCompleted = followUpCompleted;
	}

	public java.lang.Boolean getCustomerFollowUp() {
		return this.customerFollowUp;
	}

	public void setCustomerFollowUp(java.lang.Boolean customerFollowUp) {
		this.customerFollowUp = customerFollowUp;
	}

	public java.lang.String getAppIncidentDescriptiona() {
		return this.appIncidentDescriptiona;
	}

	public void setAppIncidentDescriptiona(
			java.lang.String appIncidentDescriptiona) {
		this.appIncidentDescriptiona = appIncidentDescriptiona;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public com.myteam.tts_connected_claims.stolenItemDetails getStolenItemDetails() {
		return this.stolenItemDetails;
	}

	public void setStolenItemDetails(
			com.myteam.tts_connected_claims.stolenItemDetails stolenItemDetails) {
		this.stolenItemDetails = stolenItemDetails;
	}

	public java.util.List<java.lang.String> getDocumentList() {
		return this.documentList;
	}

	public void setDocumentList(java.util.List<java.lang.String> documentList) {
		this.documentList = documentList;
	}

	public java.lang.String getIncidentCaseId() {
		return this.incidentCaseId;
	}

	public void setIncidentCaseId(java.lang.String incidentCaseId) {
		this.incidentCaseId = incidentCaseId;
	}

	public java.lang.String getNonMotorClaimStatus() {
		return this.nonMotorClaimStatus;
	}

	public void setNonMotorClaimStatus(java.lang.String nonMotorClaimStatus) {
		this.nonMotorClaimStatus = nonMotorClaimStatus;
	}

	public java.lang.Long getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(java.lang.Long sentDate) {
		this.sentDate = sentDate;
	}

	public java.util.List<java.lang.String> getTpDriverDetails() {
		return this.tpDriverDetails;
	}

	public void setTpDriverDetails(
			java.util.List<java.lang.String> tpDriverDetails) {
		this.tpDriverDetails = tpDriverDetails;
	}

	public java.lang.Boolean getVehicleDamageAreaAssessment() {
		return this.vehicleDamageAreaAssessment;
	}

	public void setVehicleDamageAreaAssessment(
			java.lang.Boolean vehicleDamageAreaAssessment) {
		this.vehicleDamageAreaAssessment = vehicleDamageAreaAssessment;
	}

	public com.myteam.tts_connected_claims.vehicleInnerDamage getVehicleInnerDamage() {
		return this.vehicleInnerDamage;
	}

	public void setVehicleInnerDamage(
			com.myteam.tts_connected_claims.vehicleInnerDamage vehicleInnerDamage) {
		this.vehicleInnerDamage = vehicleInnerDamage;
	}

	public com.myteam.tts_connected_claims.vehicleOuterDamage getVehicleOuterDamage() {
		return this.vehicleOuterDamage;
	}

	public void setVehicleOuterDamage(
			com.myteam.tts_connected_claims.vehicleOuterDamage vehicleOuterDamage) {
		this.vehicleOuterDamage = vehicleOuterDamage;
	}

	public com.myteam.tts_connected_claims.coverType getCoverType() {
		return this.coverType;
	}

	public void setCoverType(com.myteam.tts_connected_claims.coverType coverType) {
		this.coverType = coverType;
	}

	public java.lang.Boolean getCompleteReview() {
		return this.completeReview;
	}

	public void setCompleteReview(java.lang.Boolean completeReview) {
		this.completeReview = completeReview;
	}

	public java.lang.String getAppAdditionalComments() {
		return this.appAdditionalComments;
	}

	public void setAppAdditionalComments(java.lang.String appAdditionalComments) {
		this.appAdditionalComments = appAdditionalComments;
	}

	public assessments(
			java.lang.String activeUser,
			java.lang.Long assessmentCaseTime,
			java.lang.String assessmentOwner,
			java.lang.String assessmentId,
			java.lang.String assessmentCreator,
			java.lang.String brand,
			java.lang.String brandDescription,
			java.lang.String caseStatus,
			java.lang.String containerId,
			java.math.BigInteger createdAt,
			java.lang.String createdBy,
			java.lang.String delayReason,
			java.lang.String delayType,
			java.lang.Long dueDate,
			java.lang.String imsPrefix,
			java.lang.String processId,
			java.lang.Long processInstanceId,
			java.lang.String subBrand,
			java.lang.String subBrandDescription,
			com.myteam.tts_connected_claims.assessmentCustomerDetails assessmentCustomerDetails,
			com.myteam.tts_connected_claims.assessmentPolicyDetails assessmentPolicyDetails,
			com.myteam.tts_connected_claims.claimDetails claimDetails,
			com.myteam.tts_connected_claims.channel channel,
			com.myteam.tts_connected_claims.classification classification,
			java.lang.Boolean resendAssessment,
			java.lang.String riskItemSequenceNumber,
			java.lang.String personSequenceNumber,
			java.lang.String caseClosedReason,
			java.util.List<java.lang.String> ownerGroupList,
			com.myteam.tts_connected_claims.claimsData claimsData,
			java.lang.String vastatus,
			java.lang.String triggerSource,
			java.lang.Boolean taskDashBoard,
			java.lang.String requestType,
			java.lang.Boolean refferedToLA,
			java.util.List<com.myteam.tts_connected_claims.timeline> timeline,
			java.util.List<java.lang.String> groupList,
			java.lang.Boolean completedByLA,
			java.lang.String caseCancelledReason,
			java.lang.Boolean followUpCompleted,
			java.lang.Boolean customerFollowUp,
			java.lang.String appIncidentDescriptiona,
			java.lang.String location,
			com.myteam.tts_connected_claims.stolenItemDetails stolenItemDetails,
			java.util.List<java.lang.String> documentList,
			java.lang.String incidentCaseId,
			java.lang.String nonMotorClaimStatus,
			java.lang.Long sentDate,
			java.util.List<java.lang.String> tpDriverDetails,
			java.lang.Boolean vehicleDamageAreaAssessment,
			com.myteam.tts_connected_claims.vehicleInnerDamage vehicleInnerDamage,
			com.myteam.tts_connected_claims.vehicleOuterDamage vehicleOuterDamage,
			com.myteam.tts_connected_claims.coverType coverType,
			java.lang.Boolean completeReview,
			java.lang.String appAdditionalComments) {
		this.activeUser = activeUser;
		this.assessmentCaseTime = assessmentCaseTime;
		this.assessmentOwner = assessmentOwner;
		this.assessmentId = assessmentId;
		this.assessmentCreator = assessmentCreator;
		this.brand = brand;
		this.brandDescription = brandDescription;
		this.caseStatus = caseStatus;
		this.containerId = containerId;
		this.createdAt = createdAt;
		this.createdBy = createdBy;
		this.delayReason = delayReason;
		this.delayType = delayType;
		this.dueDate = dueDate;
		this.imsPrefix = imsPrefix;
		this.processId = processId;
		this.processInstanceId = processInstanceId;
		this.subBrand = subBrand;
		this.subBrandDescription = subBrandDescription;
		this.assessmentCustomerDetails = assessmentCustomerDetails;
		this.assessmentPolicyDetails = assessmentPolicyDetails;
		this.claimDetails = claimDetails;
		this.channel = channel;
		this.classification = classification;
		this.resendAssessment = resendAssessment;
		this.riskItemSequenceNumber = riskItemSequenceNumber;
		this.personSequenceNumber = personSequenceNumber;
		this.caseClosedReason = caseClosedReason;
		this.ownerGroupList = ownerGroupList;
		this.claimsData = claimsData;
		this.vastatus = vastatus;
		this.triggerSource = triggerSource;
		this.taskDashBoard = taskDashBoard;
		this.requestType = requestType;
		this.refferedToLA = refferedToLA;
		this.timeline = timeline;
		this.groupList = groupList;
		this.completedByLA = completedByLA;
		this.caseCancelledReason = caseCancelledReason;
		this.followUpCompleted = followUpCompleted;
		this.customerFollowUp = customerFollowUp;
		this.appIncidentDescriptiona = appIncidentDescriptiona;
		this.location = location;
		this.stolenItemDetails = stolenItemDetails;
		this.documentList = documentList;
		this.incidentCaseId = incidentCaseId;
		this.nonMotorClaimStatus = nonMotorClaimStatus;
		this.sentDate = sentDate;
		this.tpDriverDetails = tpDriverDetails;
		this.vehicleDamageAreaAssessment = vehicleDamageAreaAssessment;
		this.vehicleInnerDamage = vehicleInnerDamage;
		this.vehicleOuterDamage = vehicleOuterDamage;
		this.coverType = coverType;
		this.completeReview = completeReview;
		this.appAdditionalComments = appAdditionalComments;
	}

}