package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class channel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("appUUID")
	private java.lang.String appUUID;
	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;
	@org.kie.api.definition.type.Label("appAvailable")
	private java.lang.Boolean appAvailable;
	@org.kie.api.definition.type.Label("mode")
	private java.util.List<java.lang.String> mode;

	@org.kie.api.definition.type.Label("preferredContactNumber")
	private java.lang.String preferredContactNumber;

	@org.kie.api.definition.type.Label("contactTime")
	private java.lang.String contactTime;

	@org.kie.api.definition.type.Label(value = "surname")
	private java.lang.String surname;

	@org.kie.api.definition.type.Label(value = "relationship")
	private java.lang.String relationship;

	@org.kie.api.definition.type.Label(value = "userProfile")
	private java.lang.String userProfile;

	@org.kie.api.definition.type.Label(value = "title")
	private java.lang.String title;

	public channel() {
	}

	public java.lang.String getAppUUID() {
		return this.appUUID;
	}

	public void setAppUUID(java.lang.String appUUID) {
		this.appUUID = appUUID;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.Boolean getAppAvailable() {
		return this.appAvailable;
	}

	public void setAppAvailable(java.lang.Boolean appAvailable) {
		this.appAvailable = appAvailable;
	}

	public java.util.List<java.lang.String> getMode() {
		return this.mode;
	}

	public void setMode(java.util.List<java.lang.String> mode) {
		this.mode = mode;
	}

	public java.lang.String getPreferredContactNumber() {
		return this.preferredContactNumber;
	}

	public void setPreferredContactNumber(
			java.lang.String preferredContactNumber) {
		this.preferredContactNumber = preferredContactNumber;
	}

	public java.lang.String getContactTime() {
		return this.contactTime;
	}

	public void setContactTime(java.lang.String contactTime) {
		this.contactTime = contactTime;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(java.lang.String relationship) {
		this.relationship = relationship;
	}

	public java.lang.String getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(java.lang.String userProfile) {
		this.userProfile = userProfile;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public channel(java.lang.String appUUID, java.lang.String contactNumber,
			java.lang.Boolean appAvailable,
			java.util.List<java.lang.String> mode,
			java.lang.String preferredContactNumber,
			java.lang.String contactTime, java.lang.String surname,
			java.lang.String relationship, java.lang.String userProfile,
			java.lang.String title) {
		this.appUUID = appUUID;
		this.contactNumber = contactNumber;
		this.appAvailable = appAvailable;
		this.mode = mode;
		this.preferredContactNumber = preferredContactNumber;
		this.contactTime = contactTime;
		this.surname = surname;
		this.relationship = relationship;
		this.userProfile = userProfile;
		this.title = title;
	}

}